export enum Role {
  ADMIN = 'ADMIN',
  TEACHER = 'TEACHER',
  STUDENT = 'STUDENT',
}

export enum AttendanceStatus {
  PRESENT = 'PRESENT',
  ABSENT = 'ABSENT',
  LATE = 'LATE',
}

export enum EventType {
  EXAM = 'EXAM',
  HOLIDAY = 'HOLIDAY',
  MEETING = 'MEETING',
  SPECIAL = 'SPECIAL',
  ACTIVITY = 'ACTIVITY',
}

export enum Quarter {
  Q1 = 'Q1',
  Q2 = 'Q2',
  Q3 = 'Q3',
  Q4 = 'Q4',
}

export enum Grade {
  A_PLUS = 'A+',
  A = 'A',
  B = 'B',
  C = 'C',
  D = 'D',
  F = 'F',
}

export enum AuditAction {
  SUBJECT_CREATED = 'SUBJECT_CREATED',
  MARKS_ENTERED = 'MARKS_ENTERED',
  MARKS_UPDATED = 'MARKS_UPDATED',
  ACADEMIC_REPORT_GENERATED = 'ACADEMIC_REPORT_GENERATED',
  STUDENT_ASSIGNED_TO_CLASS = 'STUDENT_ASSIGNED_TO_CLASS',
  ATTENDANCE_MARKED = 'ATTENDANCE_MARKED',
  ATTENDANCE_UPDATED = 'ATTENDANCE_UPDATED',
  SESSION_CREATED = 'SESSION_CREATED',
  SESSION_UPDATED = 'SESSION_UPDATED',
  REPORT_GENERATED = 'REPORT_GENERATED',
  PROFILE_UPDATED = 'PROFILE_UPDATED',
  USER_CREATED = 'USER_CREATED',
  CLASS_CREATED = 'CLASS_CREATED',
  NOTE_UPLOADED = 'NOTE_UPLOADED',
  SCHEDULE_CREATED = 'SCHEDULE_CREATED',
  EVENT_CREATED = 'EVENT_CREATED',
  ACADEMIC_STRUCTURE_CREATED = 'ACADEMIC_STRUCTURE_CREATED',
  ACADEMIC_STRUCTURE_UPDATED = 'ACADEMIC_STRUCTURE_UPDATED',
}

export enum AssignmentStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  CLOSED = 'CLOSED',
}

export enum SubmissionStatus {
  SUBMITTED = 'SUBMITTED',
  COMPLETED = 'COMPLETED',
  NEEDS_WORK = 'NEEDS_WORK',
}
